"""职责：新增当前账号工作空间的本公司资料表。
实现：创建独立一对一资料及版本，不迁移或修改现有客户、目标画像和邮箱数据。
关联：accounts.models.CompanyProfile，依赖已创建的 User。
目录：
- Migration：建立本公司资料表。
变量索引：
- Migration.dependencies：账号初始迁移依赖。
- Migration.operations：新增表的字段与关系定义。
"""

# Generated by Django 5.2.17 on 2026-09-20 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# 功能：建立本公司资料表。
# 逻辑：由 Django migrate 创建表及 owner 唯一关系。
# 约束：导入不执行迁移；反向迁移会删除本表资料。
class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("company_name", models.CharField(max_length=240)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("website", models.URLField(blank=True, max_length=500)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=80)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True, max_length=5000)),
                ("revision", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
