"""Responsibility: Add the company-information table for the current account workspace.
Implementation: Create an independent one-to-one profile and version without migrating or changing existing customer, target-profile, or mailbox data.
Relationships: ``accounts.models.CompanyProfile``; depends on the created ``User``.
Directory:
- Migration: Create the company-information table.
Variable index:
- Migration.dependencies: Accounts initial-migration dependency.
- Migration.operations: Field and relation definitions for the new table.
"""

# Generated by Django 5.2.17 on 2026-09-20 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# Function: Create the company-information table.
# Logic: Django ``migrate`` creates the table and the unique owner relation.
# Constraints: Importing does not execute migration; reverse migration deletes this table's information.
class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("company_name", models.CharField(max_length=240)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("website", models.URLField(blank=True, max_length=500)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=80)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True, max_length=5000)),
                ("revision", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
