"""职责：增加四步引导资料、私有附件和公司规模。
实现：创建账号隔离资料表与数据库附件，既有账号不生成引导记录。
关联：accounts.models 与 onboarding API；不改变已有评分或 CRM 数据。
目录：
- Migration：声明新增表及字段。
变量索引：
- Migration.dependencies：公司资料迁移依赖。
- Migration.operations：引导资料、附件和规模字段定义。
"""

# Generated by Django 5.2.17 on 2026-09-20 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


# 功能：声明四步引导的数据结构。
# 逻辑：仅新增字段和表，不修改历史账号与业务记录。
# 约束：由 migrate 显式应用；反向迁移会删除新增资料。
class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_company_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesSetup",
            fields=[
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("personal", models.JSONField(default=dict)),
                ("products", models.JSONField(default=list)),
                ("solutions", models.JSONField(default=list)),
                ("completed", models.BooleanField(default=False)),
                ("revision", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="size_band",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name="SetupDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=240)),
                ("content_type", models.CharField(max_length=80)),
                ("content", models.BinaryField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
