"""Responsibility: Add four-step onboarding information, private attachments, and company size.
Implementation: Create account-isolated setup-information tables and database attachments without generating onboarding records for existing accounts.
Relationships: ``accounts.models`` and the onboarding API; does not change existing scoring or CRM data.
Directory:
- Migration: Declare new tables and fields.
Variable index:
- Migration.dependencies: Company-information migration dependency.
- Migration.operations: Definitions for onboarding information, attachments, and the size field.
"""

# Generated by Django 5.2.17 on 2026-09-20 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


# Function: Declare data structures for four-step onboarding.
# Logic: Add only fields and tables without modifying historical account or business records.
# Constraints: Applied explicitly by ``migrate``; reverse migration deletes the new information.
class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_company_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesSetup",
            fields=[
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("personal", models.JSONField(default=dict)),
                ("products", models.JSONField(default=list)),
                ("solutions", models.JSONField(default=list)),
                ("completed", models.BooleanField(default=False)),
                ("revision", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="size_band",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name="SetupDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=240)),
                ("content_type", models.CharField(max_length=80)),
                ("content", models.BinaryField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
