"""职责：创建邮件理解业务的首批数据表及唯一约束。
实现：依赖项目 User，建立邮箱、公司、联系人、邮件、抽取、分析、评分、任务和凭证表。
关联：对应 apps.crm.models；迁移由 Django 执行，模型代码是后续迁移的来源。
目录：
- Migration：建立当前业务实体对应的 PostgreSQL 结构。
变量索引：
- Migration.dependencies：依赖自定义用户模型的迁移。
- Migration.initial：声明初始迁移。
- Migration.operations：按依赖顺序建表、增加外键和唯一约束。
"""
# Generated by Django 5.2.17 on 2026-09-12 04:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


# 功能：建立当前业务实体对应的 PostgreSQL 结构。
# 逻辑：按 operations 顺序创建表与唯一约束，模型字段保持 Django 生成结果。
# 约束：仅 migrate 时执行；反向迁移将删除表和数据，不在导入时运行。
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_version", models.CharField(max_length=160)),
                ("revision", models.PositiveIntegerField()),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AgentCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("digest", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt_version", models.CharField(max_length=100)),
                ("payload", models.JSONField()),
                ("provider", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="crm.analysisinput",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("group_key", models.CharField(max_length=320)),
                ("name", models.CharField(blank=True, max_length=240, null=True)),
                ("domains", models.JSONField(default=list)),
                ("crm_status", models.CharField(default="unregistered", max_length=20)),
                ("customer", models.JSONField(default=dict)),
                ("tickets", models.JSONField(default=list)),
                ("quotes", models.JSONField(default=list)),
                ("orders", models.JSONField(default=list)),
                ("revision", models.PositiveIntegerField(default=0)),
                ("external_version", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="analysisinput",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inputs",
                to="crm.company",
            ),
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(blank=True, max_length=240, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="crm.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "dedupe_key",
                    models.CharField(max_length=400, primary_key=True, serialize=False),
                ),
                ("payload", models.JSONField()),
                ("sent_at", models.DateTimeField()),
                ("received_at", models.DateTimeField()),
                ("direction", models.CharField(max_length=12)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="crm.company",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="crm.contact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Extraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt_version", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=30)),
                ("facts", models.JSONField(null=True)),
                ("error", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extractions",
                        to="crm.email",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("trigger", models.CharField(max_length=40)),
                ("revision", models.PositiveIntegerField()),
                ("status", models.CharField(default="pending", max_length=16)),
                ("enqueued_at", models.DateTimeField(auto_now_add=True)),
                ("attempt", models.PositiveIntegerField(default=0)),
                ("lease_until", models.DateTimeField(null=True)),
                ("lease_token", models.UUIDField(null=True)),
                ("report", models.JSONField(null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="crm.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mailbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("address", models.EmailField(max_length=254)),
                ("sync_state", models.JSONField(default=dict)),
                ("version", models.PositiveIntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="email",
            name="mailbox",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="crm.mailbox",
            ),
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload", models.JSONField()),
                ("score_version", models.CharField(max_length=100)),
                ("value", models.PositiveSmallIntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="crm.analysis",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="analysis",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "prompt_version"), name="crm_analysis_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.UniqueConstraint(
                fields=("owner", "group_key"), name="crm_owner_group"
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisinput",
            constraint=models.UniqueConstraint(
                fields=("company", "input_version"), name="crm_input_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                fields=("company", "email"), name="crm_company_contact"
            ),
        ),
        migrations.AddConstraint(
            model_name="extraction",
            constraint=models.UniqueConstraint(
                fields=("email", "prompt_version"), name="crm_extract_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="mailbox",
            constraint=models.UniqueConstraint(
                fields=("owner", "address"), name="crm_owner_mailbox"
            ),
        ),
    ]
