"""职责：增加邮件分类和持久同步任务结构。
实现：追加字段、批次及逐封任务表和唯一约束，不删除原文或既有业务记录。
关联：crm.models 和 processing_models；历史分类由 classify_emails 显式回填。
目录：
- preserve_sync_requests：把旧邮箱排队状态迁移为持久批次。
- Migration：应用分类与同步结构迁移。
变量索引：
- Migration.dependencies：既有 CRM 迁移与用户模型依赖。
- Migration.operations：追加结构与约束的迁移操作。
"""
# Generated by Django 5.2.17 on 2026-09-13 07:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


# 功能：保存升级前尚未结束的邮箱同步请求。
# 输入：`apps` 为历史模型注册表，`schema_editor` 为迁移连接。
# 输出：无；queued 请求转成新批次，旧 running 显式标记中断。
# 逻辑：仅处理没有批次身份的活动旧状态，保留原游标与业务数据。
# 约束：不运行 Gmail、不自动重试旧 running；回滚不删除邮件。
def preserve_sync_requests(apps, schema_editor):
    Mailbox = apps.get_model("crm", "Mailbox")
    Run = apps.get_model("crm", "MailboxSyncRun")
    for mailbox in Mailbox.objects.using(schema_editor.connection.alias).filter(sync_state__status__in=["sync_requested", "sync_running"]).iterator():
        was_running = mailbox.sync_state.get("status") == "sync_running"
        run = Run.objects.using(schema_editor.connection.alias).create(mailbox_id=mailbox.pk, status="failed" if was_running else "queued",
            finished_at=timezone.now() if was_running else None,
            error={"code": "worker_migration", "message": "旧执行进程已替换，请明确重试。"} if was_running else None)
        mailbox.sync_state = {**mailbox.sync_state, "run_id": str(run.pk), "status": "failed" if was_running else "sync_requested"}
        mailbox.version += 1
        mailbox.save(using=schema_editor.connection.alias, update_fields=["sync_state", "version"])


# 功能：应用持久处理数据结构。
# 逻辑：Django 创建字段、表与唯一约束，旧邮件先保持原可见性。
# 约束：分类回填由显式命令执行；不修改事实或交易数据。
class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_legacy_fact_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="business_classification",
            field=models.CharField(default="business", max_length=24),
        ),
        migrations.AddField(
            model_name="email",
            name="classification_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="email",
            name="classification_source",
            field=models.CharField(default="rule", max_length=12),
        ),
        migrations.AddField(
            model_name="email",
            name="review_revision",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="email",
            name="review_status",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="email",
            name="reviewed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="email",
            name="reviewed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_customer_emails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="MailboxSyncRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(default="queued", max_length=16)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("lease_until", models.DateTimeField(null=True)),
                ("lease_token", models.UUIDField(null=True)),
                ("error", models.JSONField(null=True)),
                ("result", models.JSONField(default=dict)),
                ("message_ids", models.JSONField(default=list)),
                (
                    "mailbox",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_runs",
                        to="crm.mailbox",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailProcessingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("gmail_message_id", models.CharField(max_length=200)),
                ("dedupe_key", models.CharField(max_length=400)),
                ("stage", models.CharField(default="discovered", max_length=20)),
                ("status", models.CharField(default="pending", max_length=16)),
                ("attempt", models.PositiveIntegerField(default=0)),
                ("error", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.company",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_jobs",
                        to="crm.mailboxsyncrun",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="mailboxsyncrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["queued", "running"])),
                fields=("mailbox",),
                name="crm_active_mailbox_run",
            ),
        ),
        migrations.AddConstraint(
            model_name="emailprocessingjob",
            constraint=models.UniqueConstraint(
                fields=("run", "gmail_message_id"), name="crm_run_message"
            ),
        ),
        migrations.RunPython(preserve_sync_requests, migrations.RunPython.noop),
    ]
