# Generated by Django 5.2.17 on 2026-09-13 14:25

"""职责：增加原文检查点、人工修复及分析血缘持久结构。
实现：创建五个模型，并把抽取与分析唯一键扩展到修复代次和上下文 revision。
关联：crm.0005 后升级；历史原文、抽取与结果保留，既有抽取代次为零。
目录：
- Migration：声明可逆结构变更。
变量索引：
- Migration.dependencies：依赖上次持久批次迁移。
- Migration.operations：建表、外键及唯一约束变更；不执行外部服务或数据删除。
"""
import django.db.models.deletion
from django.db import migrations, models


# 功能：应用持久原文和血缘结构。
# 逻辑：先建表和调整版本约束，再关联来源与修复任务。
# 约束：无业务数据重分类；回滚前须处理多代修复数据以满足旧唯一键。
class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_persistent_processing"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractionRepair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_revision", models.PositiveIntegerField()),
                ("status", models.CharField(default="pending", max_length=16)),
                ("lease_until", models.DateTimeField(null=True)),
                ("error", models.CharField(default="", max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SnapshotInvalidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SnapshotSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_revision", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="StoredMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(max_length=200)),
                ("raw", models.JSONField(default=dict)),
                ("submission", models.JSONField(default=dict)),
                ("status", models.CharField(default="pending", max_length=16)),
                ("prompt_version", models.CharField(default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SyncCheckpoint",
            fields=[
                (
                    "mailbox",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="checkpoint",
                        serialize=False,
                        to="crm.mailbox",
                    ),
                ),
                ("cursor", models.CharField(default="", max_length=200)),
                ("anchor", models.CharField(default="", max_length=200)),
                ("page_token", models.TextField(default="")),
                ("backfill_complete", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="analysisinput",
            name="crm_input_version",
        ),
        migrations.RemoveConstraint(
            model_name="extraction",
            name="crm_extract_version",
        ),
        migrations.AddField(
            model_name="extraction",
            name="repair_generation",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="analysisinput",
            constraint=models.UniqueConstraint(
                fields=("company", "input_version", "revision"),
                name="crm_input_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="extraction",
            constraint=models.UniqueConstraint(
                fields=("email", "prompt_version", "repair_generation"),
                name="crm_extract_generation",
            ),
        ),
        migrations.AddField(
            model_name="extractionrepair",
            name="email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repairs",
                to="crm.email",
            ),
        ),
        migrations.AddField(
            model_name="extractionrepair",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="crm.extraction"
            ),
        ),
        migrations.AddField(
            model_name="snapshotinvalidation",
            name="snapshot",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invalidation",
                to="crm.analysisinput",
            ),
        ),
        migrations.AddField(
            model_name="snapshotsource",
            name="email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snapshot_sources",
                to="crm.email",
            ),
        ),
        migrations.AddField(
            model_name="snapshotsource",
            name="extraction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="crm.extraction"
            ),
        ),
        migrations.AddField(
            model_name="snapshotsource",
            name="snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sources",
                to="crm.analysisinput",
            ),
        ),
        migrations.AddField(
            model_name="storedmessage",
            name="mailbox",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stored_messages",
                to="crm.mailbox",
            ),
        ),
        migrations.AddConstraint(
            model_name="extractionrepair",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "running"])),
                fields=("email",),
                name="crm_active_repair",
            ),
        ),
        migrations.AddConstraint(
            model_name="snapshotsource",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "email"), name="crm_snapshot_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="storedmessage",
            constraint=models.UniqueConstraint(
                fields=("mailbox", "message_id"), name="crm_stored_message"
            ),
        ),
    ]
