# Generated by Django 5.2.17 on 2026-09-13 14:25

"""Responsibility: Add durable source checkpoints, manual repairs, and analysis-lineage structures.
Implementation: Create five models and extend extraction and analysis unique keys with repair generation and context revision.
Relationships: Upgrades after crm.0005; preserves historical sources, extractions, and results, with existing extraction generation set to zero.
Directory:
- Migration: Declares reversible schema changes.
Variable index:
- Migration.dependencies: Dependency on the prior persistent-batch migration.
- Migration.operations: Creates tables and changes foreign keys and uniqueness constraints without calling external services or deleting data.
"""
import django.db.models.deletion
from django.db import migrations, models


# Function: Apply durable source and lineage structures.
# Logic: First create tables and adjust version constraints, then associate sources and repair jobs.
# Constraints: Does not reclassify business data; multi-generation repair data must be handled before rollback can satisfy the former unique key.
class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_persistent_processing"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractionRepair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_revision", models.PositiveIntegerField()),
                ("status", models.CharField(default="pending", max_length=16)),
                ("lease_until", models.DateTimeField(null=True)),
                ("error", models.CharField(default="", max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SnapshotInvalidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SnapshotSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_revision", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="StoredMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(max_length=200)),
                ("raw", models.JSONField(default=dict)),
                ("submission", models.JSONField(default=dict)),
                ("status", models.CharField(default="pending", max_length=16)),
                ("prompt_version", models.CharField(default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SyncCheckpoint",
            fields=[
                (
                    "mailbox",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="checkpoint",
                        serialize=False,
                        to="crm.mailbox",
                    ),
                ),
                ("cursor", models.CharField(default="", max_length=200)),
                ("anchor", models.CharField(default="", max_length=200)),
                ("page_token", models.TextField(default="")),
                ("backfill_complete", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="analysisinput",
            name="crm_input_version",
        ),
        migrations.RemoveConstraint(
            model_name="extraction",
            name="crm_extract_version",
        ),
        migrations.AddField(
            model_name="extraction",
            name="repair_generation",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="analysisinput",
            constraint=models.UniqueConstraint(
                fields=("company", "input_version", "revision"),
                name="crm_input_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="extraction",
            constraint=models.UniqueConstraint(
                fields=("email", "prompt_version", "repair_generation"),
                name="crm_extract_generation",
            ),
        ),
        migrations.AddField(
            model_name="extractionrepair",
            name="email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repairs",
                to="crm.email",
            ),
        ),
        migrations.AddField(
            model_name="extractionrepair",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="crm.extraction"
            ),
        ),
        migrations.AddField(
            model_name="snapshotinvalidation",
            name="snapshot",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invalidation",
                to="crm.analysisinput",
            ),
        ),
        migrations.AddField(
            model_name="snapshotsource",
            name="email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snapshot_sources",
                to="crm.email",
            ),
        ),
        migrations.AddField(
            model_name="snapshotsource",
            name="extraction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="crm.extraction"
            ),
        ),
        migrations.AddField(
            model_name="snapshotsource",
            name="snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sources",
                to="crm.analysisinput",
            ),
        ),
        migrations.AddField(
            model_name="storedmessage",
            name="mailbox",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stored_messages",
                to="crm.mailbox",
            ),
        ),
        migrations.AddConstraint(
            model_name="extractionrepair",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "running"])),
                fields=("email",),
                name="crm_active_repair",
            ),
        ),
        migrations.AddConstraint(
            model_name="snapshotsource",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "email"), name="crm_snapshot_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="storedmessage",
            constraint=models.UniqueConstraint(
                fields=("mailbox", "message_id"), name="crm_stored_message"
            ),
        ),
    ]
