"""职责：新增 QQ 加密凭证与独立 IMAP 检查点。
实现：只创建两张关联 Mailbox 的表，不修改 Gmail 数据或现有邮件。
关联：依赖 crm.0006；qq_models 定义当前模型。
目录：
- Migration：声明可逆的 QQ 表结构变更。
变量索引：
- Migration.dependencies：要求原持久消息和血缘迁移已应用。
- Migration.operations：创建 QQSyncCheckpoint 和 QQCredential。
"""
# Generated by Django 5.2.17 on 2026-09-14 10:15

import django.db.models.deletion
from django.db import migrations, models


# 功能：建立 QQ 持久结构。
# 逻辑：新增凭证和检查点的一对一表。
# 约束：无数据回填或外部调用；回滚将移除 QQ 连接及检查点。
class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_durable_lineage"),
    ]

    operations = [
        migrations.CreateModel(
            name="QQSyncCheckpoint",
            fields=[
                (
                    "mailbox",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="qq_checkpoint",
                        serialize=False,
                        to="crm.mailbox",
                    ),
                ),
                ("folders", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="QQCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encrypted_code", models.TextField()),
                ("authorized_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mailbox",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qq_credential",
                        to="crm.mailbox",
                    ),
                ),
            ],
        ),
    ]
