"""Responsibility: Add encrypted QQ credentials and an independent IMAP checkpoint.
Implementation: Create only two tables related to Mailbox without changing Gmail data or existing emails.
Relationships: Depends on crm.0006; qq_models defines the current models.
Directory:
- Migration: Declares reversible QQ schema changes.
Variable index:
- Migration.dependencies: Requires prior durable-message and lineage migrations.
- Migration.operations: Creates QQSyncCheckpoint and QQCredential.
"""
# Generated by Django 5.2.17 on 2026-09-14 10:15

import django.db.models.deletion
from django.db import migrations, models


# Function: Create QQ durable structures.
# Logic: Add one-to-one tables for credentials and checkpoints.
# Constraints: Includes no data backfill or external calls; rollback removes QQ connections and checkpoints.
class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_durable_lineage"),
    ]

    operations = [
        migrations.CreateModel(
            name="QQSyncCheckpoint",
            fields=[
                (
                    "mailbox",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="qq_checkpoint",
                        serialize=False,
                        to="crm.mailbox",
                    ),
                ),
                ("folders", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="QQCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encrypted_code", models.TextField()),
                ("authorized_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mailbox",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qq_credential",
                        to="crm.mailbox",
                    ),
                ),
            ],
        ),
    ]
