"""Responsibility: Add account-isolated global-event and news fact tables.
Implementation: Create only WorldEvent/WorldNews tables and time indexes, inheriting version and archival fields.
Relationships: sales.models and the generic record interface; preserve existing scoring and demonstration data.
Directory:
- Migration: Declare new-table operations.
Variable index:
- Migration.dependencies: Depend on sales context and the account model.
- Migration.operations: Two CreateModel operations without data rewrites.
"""
# Generated by Django 5.2.17 on 2026-09-20 17:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


# Function: Create event and news fact tables.
# Logic: Use Django-generated fields, foreign keys, and indexes.
# Constraints: No content collection or demonstration-data backfill; reversal drops the new tables.
class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_l4_priority_context"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorldEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=0)),
                ("archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=240)),
                (
                    "event_type",
                    models.CharField(
                        choices=[("exhibition", "展会"), ("sales", "销售活动")],
                        max_length=20,
                    ),
                ),
                ("country", models.CharField(max_length=2)),
                ("city", models.CharField(max_length=120)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("starts_at", models.DateTimeField(db_index=True)),
                ("ends_at", models.DateTimeField()),
                ("registration_deadline", models.DateTimeField(blank=True, null=True)),
                ("source_url", models.URLField(max_length=2000)),
                ("description", models.TextField(blank=True)),
                ("onsite", models.JSONField(blank=True, default=list)),
                ("suggested_actions", models.JSONField(blank=True, default=list)),
                ("opportunity_ids", models.JSONField(blank=True, default=list)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorldNews",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=0)),
                ("archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=240)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("regulation", "监管"),
                            ("industry", "产业"),
                            ("competition", "竞争"),
                            ("price", "价格"),
                        ],
                        max_length=20,
                    ),
                ),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("published_at", models.DateTimeField(db_index=True)),
                ("source_url", models.URLField(max_length=2000)),
                ("summary", models.TextField(blank=True)),
                ("content", models.TextField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
