"""Responsibility: Create opportunity signal/score tables and event/news source markers.
Implementation: Add independent tables and optional source fields; mark existing records manual without migrating or rewriting scores.
Relationships: sales.algorithm_models and world-insight queries.
Directory:
- Migration: Declare database changes.
Variable index:
- Migration.dependencies: Depend on the original event/news migration and user model.
- Migration.operations: Structural operations adding tables/fields and permitting empty sources.
"""
# Generated by Django 5.2.17 on 2026-09-22 01:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


# Function: Declare the support-layer migration.
# Logic: Add storage structures without initializing data.
# Constraints: Fictional data is written by a separate explicit command.
class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_mailboxsyncrun_sync_options"),
        ("sales", "0007_world_insights"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="worldevent",
            name="data_source",
            field=models.CharField(default="manual", max_length=30),
        ),
        migrations.AddField(
            model_name="worldnews",
            name="data_source",
            field=models.CharField(default="manual", max_length=30),
        ),
        migrations.AlterField(
            model_name="worldevent",
            name="source_url",
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="worldnews",
            name="source_url",
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.CreateModel(
            name="OpportunityPriority",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=0)),
                ("archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "priority_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("score_breakdown", models.JSONField(blank=True, default=dict)),
                ("top_reasons", models.JSONField(blank=True, default=list)),
                ("evidence", models.JSONField(blank=True, default=list)),
                ("recommended_next_action", models.TextField(blank=True)),
                ("scored_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("score_version", models.CharField(blank=True, max_length=100)),
                ("data_source", models.CharField(default="agent", max_length=30)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_records",
                        to="crm.company",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="priority_results",
                        to="sales.opportunity",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OpportunitySignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=0)),
                ("archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("signal_type", models.CharField(max_length=100)),
                ("signal_value", models.JSONField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("source_type", models.CharField(blank=True, max_length=50)),
                ("source_id", models.CharField(blank=True, max_length=500)),
                ("evidence_text", models.TextField(blank=True)),
                (
                    "detected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("status", models.CharField(default="ACTIVE", max_length=50)),
                ("data_source", models.CharField(default="agent", max_length=30)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_records",
                        to="crm.company",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="sales.opportunity",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
