"""职责：创建商机信号/评分表及活动资讯来源标记。
实现：新增独立表和可选来源字段，已有记录标记 manual，不迁移或改写评分。
关联：sales.algorithm_models 与世界洞察查询。
目录：
- Migration：声明数据库变化。
变量索引：
- Migration.dependencies：依赖原活动资讯迁移及用户模型。
- Migration.operations：新增表与字段、允许来源为空的结构操作。
"""
# Generated by Django 5.2.17 on 2026-09-22 01:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


# 功能：声明支持层迁移。
# 逻辑：新增存储结构，不执行数据初始化。
# 约束：虚拟数据由独立显式命令写入。
class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_mailboxsyncrun_sync_options"),
        ("sales", "0007_world_insights"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="worldevent",
            name="data_source",
            field=models.CharField(default="manual", max_length=30),
        ),
        migrations.AddField(
            model_name="worldnews",
            name="data_source",
            field=models.CharField(default="manual", max_length=30),
        ),
        migrations.AlterField(
            model_name="worldevent",
            name="source_url",
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="worldnews",
            name="source_url",
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.CreateModel(
            name="OpportunityPriority",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=0)),
                ("archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "priority_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("score_breakdown", models.JSONField(blank=True, default=dict)),
                ("top_reasons", models.JSONField(blank=True, default=list)),
                ("evidence", models.JSONField(blank=True, default=list)),
                ("recommended_next_action", models.TextField(blank=True)),
                ("scored_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("score_version", models.CharField(blank=True, max_length=100)),
                ("data_source", models.CharField(default="agent", max_length=30)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_records",
                        to="crm.company",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="priority_results",
                        to="sales.opportunity",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OpportunitySignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=0)),
                ("archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("signal_type", models.CharField(max_length=100)),
                ("signal_value", models.JSONField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("source_type", models.CharField(blank=True, max_length=50)),
                ("source_id", models.CharField(blank=True, max_length=500)),
                ("evidence_text", models.TextField(blank=True)),
                (
                    "detected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("status", models.CharField(default="ACTIVE", max_length=50)),
                ("data_source", models.CharField(default="agent", max_length=30)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_records",
                        to="crm.company",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="sales.opportunity",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
