"""Responsibility: Add optional source-backed geography to public news.
Implementation: Add blank city/evidence/source URL and nullable coordinates without inventing locations for legacy news.
Relationships: WorldNewsSerializer validates complete groups; the map includes only explicitly located news.
Directory:
- Migration: Add five optional news location fields.
Variable index:
- Migration.dependencies: Source amount schema prerequisite.
- Migration.operations: Additive fields preserving existing news and amounts.
"""
# Generated by Django 5.2.17 on 2026-09-27 04:42

from django.db import migrations, models


# Function: Extend news storage without a geographical backfill.
# Logic: Legacy records remain unlocated until an explicit source review.
# Constraints: No network access, inferred headquarters or destructive operations.
class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0011_source_amounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="worldnews",
            name="city",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="worldnews",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="worldnews",
            name="location_evidence",
            field=models.CharField(blank=True, default="", max_length=600),
        ),
        migrations.AddField(
            model_name="worldnews",
            name="location_source_url",
            field=models.URLField(blank=True, default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="worldnews",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
